# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191129_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
